version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.local.old
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: bash -c "rm -f /rails/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - bundle-data:/usr/local/bundle

  css:
    build:
      context: .
      dockerfile: Dockerfile.local.old
    command: ['bin/rails', 'tailwindcss:watch']
    tty: true
    volumes:
      - .:/app
      - bundle-data:/usr/local/bundle

volumes:
  postgres-data:
  bundle-data:
